In [82]:
import numpy as np
import sys
import array

## Домашняя работа №1:


## 1. Какие ещё существует коды типов?
 

## 2. Напишите код, подобный приведённому выше, но с другим типом

In [86]:
my_a = array.array('u', ['c', '~', 'ё'])
print(my_a)

print(sys.getsizeof(a1))
print(type(a1))

array('u', 'c~ё')
92
<class 'array.array'>


## 3. Напишите код для создания массива с 5 значениями, располагающимися через равные интервалы в диапазоне от 0 до 1

In [96]:
my_b = np.linspace(0, 1, 5)
print(my_b)

[0.   0.25 0.5  0.75 1.  ]


## 4. Напишите код для создания массива с 5 равномерно распределенными случайными значениями в диапазоне от 0 до 1


In [97]:
my_c = np.random.rand(5)
print(my_c)

[0.14038694 0.19810149 0.80074457 0.96826158 0.31342418]


## 5. Напишите код для создания массива с 5 нормально распределенными случайными значениями с мат. ожиданием равным 0 и дисперсией 1

In [98]:
my_d = np.random.normal(size=5)
print(my_d)

[ 0.7299756   0.37299379  0.53381091 -0.0919733   1.91382039]


## 6. Напишите код для создания массива с 5 случайными целыми числами в диапазоне от [0 до 10)

In [99]:
my_e = np.random.randint(10, size=5)
print(my_e)

[1 4 0 3 9]


## 7. Написать код для создания срезов массива 3 на 4
- первые две строки и три столбца
- первые три строки и второй столбец
- все строки и столбцы в обратном порядке
- второй столбец
- третья строка

In [123]:
my_f = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(my_f)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [124]:
print(my_f[:2, :3])

[[1 2 3]
 [5 6 7]]


In [129]:
print(my_f[:3, 1])

[ 2  6 10]


In [126]:
print(my_f[::-1, ::-1])

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


In [127]:
print(my_f[:, 1])

[ 2  6 10]


In [128]:
print(my_f[2, :])

[ 9 10 11 12]


## 8. Продемонстрируйте, как сделать срез-копию

In [133]:
a = np.arange(1, 7)
b = np.copy(a[2:4])
b[1] = 0
print(b)
print(a)

[3 0]
[1 2 3 4 5 6]


## 9. Продемонстрируйте использования newaxis для получения вектора-столбца и вектора-строки из массива

In [136]:
my_g = np.arange(1, 10)
my_g_column = my_g[:, np.newaxis]
print(my_g_column)
my_g_raw = my_g[np.newaxis, :]
print(my_g_raw)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[1 2 3 4 5 6 7 8 9]]


In [137]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6])

print (np.concatenate([x, y, z]))

[1 2 3 4 5 6]


In [140]:
y = np.array([4, 5, 6])
r1 = np.vstack([x, y])
print(r1)

[[1 2 3]
 [4 5 6]]


In [148]:
print(np.hstack([x, y]))

[1 2 3 4 5 6]


## 10. Разобраться, как работает dstack

In [152]:
my_h1  = np.dstack([x, y])
print(my_h1)
print(np.shape(my_h1))
my_h2 = np.dstack([np.vstack([x, y]), np.vstack([x, y])])
print(my_h2)
print(np.shape(my_h2))

[[[1 4]
  [2 5]
  [3 6]]]
(1, 3, 2)
[[[1 1]
  [2 2]
  [3 3]]

 [[4 4]
  [5 5]
  [6 6]]]
(2, 3, 2)


# 11. Разобраться, как работают методы split, vsplit, hsplit, dsplit

In [154]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
z = np.array([6])
xyz = np.concatenate([x, y, z])
x, y, z = np.split(xyz, [3, 5])
print(x, y, z)

[1 2 3] [4 5] [6]


In [158]:
y = np.array([4, 5, 6])
xy = np.vstack([x, y])
print(xy)
x, y = np.vsplit(xy, 2)
print(x, y)

[[1 2 3]] [[4 5 6]]
[[1 2 3]
 [4 5 6]]


In [160]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
xy = np.hstack([x, y])
print(xy)
x, y = np.hsplit(xy, 2)
print(x, y)

[1 2 3 4 5 6]
[1 2 3] [4 5 6]


In [166]:
xy  = np.dstack([x, y])
print(xy)
print()
x, y = np.dsplit(xy, 2)
print(x)
print()
print(y)

[[[1 4]
  [2 5]
  [3 6]]]

[[[1]
  [2]
  [3]]]

[[[4]
  [5]
  [6]]]


## 12. Привести примеры использования универсальных функций


In [171]:
my_i = np.ones((3, 3))
print(my_i)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [172]:
print(my_i+2)

[[3. 3. 3.]
 [3. 3. 3.]
 [3. 3. 3.]]


In [173]:
print(my_i-2)

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


In [174]:
print(-my_i)

[[-1. -1. -1.]
 [-1. -1. -1.]
 [-1. -1. -1.]]


In [175]:
print(my_i*2)

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [176]:
print(my_i/2)

[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]


In [177]:
print(my_i//2)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [178]:
print(my_i**2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [179]:
print(my_i%2)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
