In [82]:
import numpy as np
import sys
import array

## Типы данных Python:


In [83]:
x = 1
print(type(x))
print(sys.getsizeof(x))#
x = "hello"
print(type(x))
x = True
print(type(x))

<class 'int'>
28
<class 'str'>
<class 'bool'>


In [84]:
l1 = list([])
print(sys.getsizeof(l1))
l2 = list([1, 2, 3])
print(sys.getsizeof(l2))
l3 = list([1, "2", True])
print(sys.getsizeof(l3))

56
88
88


In [85]:

a1 = array.array('i', [1, 2, 3])
print(sys.getsizeof(a1))
print(type(a1))

92
<class 'array.array'>


## NumPy


In [87]:
a = np.array([1, 2, 3, 4, 5])
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


Повышающее приведение типов - приведение к наиболее большому типу в массиве

In [88]:
a = np.array([1.23, 2, 3, 4, 5])
print(type(a), a)

<class 'numpy.ndarray'> [1.23 2.   3.   4.   5.  ]


In [89]:
a = np.array([1.23, 2, 3, 4, 5], dtype=int)
print(type(a), a)

<class 'numpy.ndarray'> [1 2 3 4 5]


In [90]:
a = np.array([range(i, i+3) for i in [2, 4, 6]])
print(a)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


In [91]:
a = np.zeros(10, dtype=int)
print(a, type(a))

[0 0 0 0 0 0 0 0 0 0] <class 'numpy.ndarray'>


In [92]:
print(np.ones((3, 5), dtype=float))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [93]:
print(np.full((4, 5), 3.1415))

[[3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]
 [3.1415 3.1415 3.1415 3.1415 3.1415]]


In [94]:
print(np.arange(0, 20, 2))

[ 0  2  4  6  8 10 12 14 16 18]


In [95]:
print(np.eye(4))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


## RANDOM

In [100]:
np.random.seed(1)
x1 = np.random.randint(10, size=3)
print(x1)

[5 8 9]


In [101]:
x2 = np.random.randint(10, size=(3, 2))
print(x2)

[[5 0]
 [0 1]
 [7 6]]


In [102]:
x3 = np.random.randint(10, size=(3, 2, 2))
print(x3)

[[[9 2]
  [4 5]]

 [[2 4]
  [2 4]]

 [[7 7]
  [9 1]]]


In [103]:
print(x1.ndim, x1.shape, x1.size)
print(x2.ndim, x2.shape, x2.size)
print(x3.ndim, x3.shape, x3.size)

1 (3,) 3
2 (3, 2) 6
3 (3, 2, 2) 12


## Индексы


In [104]:
a = np.array([1, 2, 3, 4, 5])
print(a[1])

2


In [105]:
print(a[-2])

4


In [106]:
a[1] = 20

In [107]:
print(a)

[ 1 20  3  4  5]


In [108]:
a = np.array([[1, 2], [3, 4]])
print(a)

[[1 2]
 [3 4]]


In [109]:
print(a[0, 0])

1


In [110]:
print(a[-1, -1])

4


In [111]:
a[1, 0] = 100
print(a)

[[  1   2]
 [100   4]]


In [112]:
a[1, 0] = 100.99
print(a)

[[  1   2]
 [100   4]]


## Срезы

In [113]:
a = np.arange(1, 7)
print(a[:3])

[1 2 3]


In [114]:
print(a[3:])

[4 5 6]


In [115]:
print(a[1:5])

[2 3 4 5]


In [116]:
print(a[1:-1])

[2 3 4 5]


In [117]:
print(a[:6:2])

[1 3 5]


In [118]:
print(a[2::2])

[3 5]


In [120]:
print(a[::-1])

[6 5 4 3 2 1]


In [131]:
b = a[:3]
b[1] = 5
print(a)

[1 5 3 4 5 6]


## Размерности массива и объединение

In [135]:
a = np.arange(1, 13)
print(a)
print(a.reshape(3, 4))

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Векторизованные операции


In [168]:
x = np.arange(10)
print(x)
print(x*2+1)

[0 1 2 3 4 5 6 7 8 9]
[ 1  3  5  7  9 11 13 15 17 19]


In [169]:
print(np.multiply(x, 2))

[ 0  2  4  6  8 10 12 14 16 18]


## Другие ufunc
np.abs, np.sin и др. тригонометрические, np.exp, np.log


In [181]:
x = np.arange(5)
y = np.empty(10)
print(np.multiply(x, 10, out=y[::2]))
print(y)

[ 0. 10. 20. 30. 40.]
[ 0.  0. 10.  0. 20.  0. 30.  0. 40.  0.]


In [182]:
print(np.add.reduce(x))

10


In [183]:
print(np.add.accumulate(x))

[ 0  1  3  6 10]


In [184]:
print(np.multiply.outer(x, x))

[[ 0  0  0  0  0]
 [ 0  1  2  3  4]
 [ 0  2  4  6  8]
 [ 0  3  6  9 12]
 [ 0  4  8 12 16]]
