# Домашняя работа

Q1. Что надо изменить в последнем примере, чтобы он заработал без ошибок?<br>
<code>
a = np.ones((3, 2))<br>
b = np.arange(3)<br>
c = a + b<br>
</code>

In [7]:
import numpy as np

a = np.ones((3, 2))
b = np.arange(3)
b = b[:, np.newaxis]
print(b.shape)
c = a + b
print('\n', c)

(3, 1)

 [[1. 1.]
 [2. 2.]
 [3. 3.]]


Q2: См. пример для y. Вычислить количество элементов по (обеим размерностям), значения которых больше 3 и меньше 9

In [11]:
y = np.vstack((np.arange(1, 6, 1), np.arange(6, 11, 1)))
print(y)
print(np.sum(np.logical_and((y > 3),(y < 9))))
print(np.sum((y > 3) & (y < 9)))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
5
5
